# Generated by truewire — do not edit by hand.
from .get import Get


class Clips(Get):
  """Clips captured from a broadcast, by clip id, by broadcaster or by category, paged by cursor.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-clips)
  """
