# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import Pagination


class Clip(TypedDict):
  """One clip."""

  id: str
  """An ID that identifies the clip."""
  url: str
  """A URL to the clip on twitch.tv."""
  embed_url: str
  """A URL to embed the clip in an iframe."""
  broadcaster_id: str
  """The ID of the broadcaster the clip was taken from."""
  broadcaster_name: str
  """The broadcaster's display name."""
  creator_id: str
  """The ID of the user that made the clip."""
  creator_name: str
  """That user's display name."""
  video_id: str
  """The video the clip came from; an empty string where that video is not available."""
  game_id: str
  """The category being streamed when the clip was made."""
  language: str
  """The language the broadcaster streams in, as an ISO 639-1 two-letter code, or `other`."""
  title: str
  """The clip's title."""
  view_count: int
  """How many times the clip has been watched."""
  created_at: TimestampIso
  """When the clip was made."""
  thumbnail_url: str
  """A URL to a thumbnail image of the clip."""
  duration: float
  """How long the clip runs, in seconds, to a tenth of a second."""
  vod_offset: NotRequired[int | None]
  """How far into the video the clip starts, in seconds; null while the video does not exist yet, which lasts minutes after a clip is made during a live broadcast."""
  is_featured: NotRequired[bool]
  """Whether the clip is featured."""


class Request(TypedDict):
  """Which clips, and which page of them."""

  broadcaster_id: NotRequired[str]
  """The broadcaster whose clips to get. Mutually exclusive with `game_id` and `id`."""
  game_id: NotRequired[str]
  """The category whose clips to get. Mutually exclusive with `broadcaster_id` and `id`."""
  id: NotRequired[list[str]]
  """Clip ids to get, such as `AwkwardHelplessSalamanderSwiftRage`. Sent as repeated `id` query parameters; at most 100. Mutually exclusive with `broadcaster_id` and `game_id`."""
  started_at: NotRequired[TimestampIso]
  """Only clips created at or after this instant. Sent as RFC 3339."""
  ended_at: NotRequired[TimestampIso]
  """Only clips created at or before this instant. Sent as RFC 3339. Defaults to a week after `started_at`."""
  is_featured: NotRequired[bool]
  """Only featured clips when true, only unfeatured ones when false. Omit for both."""
  first: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 20."""
  after: NotRequired[str]
  """Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page."""
  before: NotRequired[str]
  """Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`."""


class ClipsFrame(TypedDict):
  """The wire frame: one page of clips, and the cursor for the next."""

  data: list[Clip]
  """The clips on this page: most viewed first by broadcaster or category, in the order asked for by id."""
  pagination: NotRequired[Pagination]


class Get(Endpoint):
  """Clips captured from broadcasts, by clip id, by broadcaster or by category. Exactly one of `id`, `broadcaster_id` and `game_id` is given. A walk over clips reaches roughly a thousand rows before Twitch stops paging; narrow it with `started_at` and `ended_at` windows to go further."""

  @overload
  def get_paged(
    self,
    *,
    broadcaster_id: str | None = None,
    game_id: str | None = None,
    id: list[str] | None = None,
    started_at: TimestampIso | None = None,
    ended_at: TimestampIso | None = None,
    is_featured: bool | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def get_paged(
    self,
    *,
    broadcaster_id: str | None = None,
    game_id: str | None = None,
    id: list[str] | None = None,
    started_at: TimestampIso | None = None,
    ended_at: TimestampIso | None = None,
    is_featured: bool | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Clip, str]: ...
  def get_paged(
    self,
    *,
    broadcaster_id: str | None = None,
    game_id: str | None = None,
    id: list[str] | None = None,
    started_at: TimestampIso | None = None,
    ended_at: TimestampIso | None = None,
    is_featured: bool | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Clip, str]:
    """Clips captured from broadcasts, by clip id, by broadcaster or by category. Exactly one of `id`, `broadcaster_id` and `game_id` is given. A walk over clips reaches roughly a thousand rows before Twitch stops paging; narrow it with `started_at` and `ended_at` windows to go further.

    Paged variant of `get`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      broadcaster_id: The broadcaster whose clips to get. Mutually exclusive with `game_id` and `id`.
      game_id: The category whose clips to get. Mutually exclusive with `broadcaster_id` and `id`.
      id: Clip ids to get, such as `AwkwardHelplessSalamanderSwiftRage`. Sent as repeated `id` query parameters; at most 100. Mutually exclusive with `broadcaster_id` and `game_id`.
      started_at: Only clips created at or after this instant. Sent as RFC 3339.
      ended_at: Only clips created at or before this instant. Sent as RFC 3339. Defaults to a week after `started_at`.
      is_featured: Only featured clips when true, only unfeatured ones when false. Omit for both.
      first: Rows per page. Range [1, 100]; defaults to 20.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-clips)
    """

    async def next(after: str) -> tuple[list[Clip], str | None]:
      response = await self.get(
        broadcaster_id=broadcaster_id,
        game_id=game_id,
        id=id,
        started_at=started_at,
        ended_at=ended_at,
        is_featured=is_featured,
        first=first,
        before=before,
        after=(after or None),
        validate=validate,
      )
      rows = response.get('data')
      state_0 = response.get('pagination')
      state = state_0.get('cursor') if state_0 is not None else None
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def get(
    self,
    *,
    broadcaster_id: str | None = None,
    game_id: str | None = None,
    id: list[str] | None = None,
    started_at: TimestampIso | None = None,
    ended_at: TimestampIso | None = None,
    is_featured: bool | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get(
    self,
    *,
    broadcaster_id: str | None = None,
    game_id: str | None = None,
    id: list[str] | None = None,
    started_at: TimestampIso | None = None,
    ended_at: TimestampIso | None = None,
    is_featured: bool | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> ClipsFrame: ...
  async def get(
    self,
    *,
    broadcaster_id: str | None = None,
    game_id: str | None = None,
    id: list[str] | None = None,
    started_at: TimestampIso | None = None,
    ended_at: TimestampIso | None = None,
    is_featured: bool | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> ClipsFrame:
    """Clips captured from broadcasts, by clip id, by broadcaster or by category. Exactly one of `id`, `broadcaster_id` and `game_id` is given. A walk over clips reaches roughly a thousand rows before Twitch stops paging; narrow it with `started_at` and `ended_at` windows to go further.

    Args:
      broadcaster_id: The broadcaster whose clips to get. Mutually exclusive with `game_id` and `id`.
      game_id: The category whose clips to get. Mutually exclusive with `broadcaster_id` and `id`.
      id: Clip ids to get, such as `AwkwardHelplessSalamanderSwiftRage`. Sent as repeated `id` query parameters; at most 100. Mutually exclusive with `broadcaster_id` and `game_id`.
      started_at: Only clips created at or after this instant. Sent as RFC 3339.
      ended_at: Only clips created at or before this instant. Sent as RFC 3339. Defaults to a week after `started_at`.
      is_featured: Only featured clips when true, only unfeatured ones when false. Omit for both.
      first: Rows per page. Range [1, 100]; defaults to 20.
      after: Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-clips)
    """
    request: Request = Request()
    if broadcaster_id is not None:
      request['broadcaster_id'] = broadcaster_id
    if game_id is not None:
      request['game_id'] = game_id
    if id is not None:
      request['id'] = id
    if started_at is not None:
      request['started_at'] = started_at
    if ended_at is not None:
      request['ended_at'] = ended_at
    if is_featured is not None:
      request['is_featured'] = is_featured
    if first is not None:
      request['first'] = first
    if after is not None:
      request['after'] = after
    if before is not None:
      request['before'] = before
    return await self.request(
      request,
      method='GET',
      path='/helix/clips',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=ClipsFrame,
    )
