# Generated by truewire — do not edit by hand.
from .get import Get


class Users(Get):
  """Accounts, by id or by login name (`GET /helix/users`).

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-users)
  """
