# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint


class Request(TypedDict):
  """Which accounts to look up."""

  id: NotRequired[list[str]]
  """User ids to look up, such as `141981764`. Sent as repeated `id` query parameters. At most 100 ids and logins together."""
  login: NotRequired[list[str]]
  """Login names to look up, such as `twitchdev`. Sent as repeated `login` query parameters. At most 100 ids and logins together."""


class User(TypedDict):
  """One account's public profile."""

  id: str
  """An ID that identifies the user."""
  login: str
  """The user's login name, lowercase."""
  display_name: str
  """The user's display name, which may differ in case from `login`."""
  type: Literal['', 'admin', 'global_mod', 'staff']
  """The type of user. `""` for a normal user."""
  broadcaster_type: Literal['', 'affiliate', 'partner']
  """The type of broadcaster. `""` for a normal broadcaster."""
  description: str
  """The user's description of their channel; an empty string if unset."""
  profile_image_url: str
  """A URL to the user's profile image."""
  offline_image_url: str
  """A URL to the image shown on the channel when it is offline; an empty string if unset."""
  created_at: TimestampIso
  """When the user's account was created."""
  email: NotRequired[str]
  """The user's verified email address. Present only when the call used a user access token carrying the `user:read:email` scope, and then only for the user that granted it."""


class UsersFrame(TypedDict):
  """The wire frame. `/helix/users` does not page, so it carries `data` alone."""

  data: list[User]
  """The accounts found, in no particular order."""


class Get(Endpoint):
  """Look up accounts by id, by login name, or by both. At most 100 across the two, and an id or login that does not exist is left out of the answer rather than erroring."""

  @overload
  async def get(
    self,
    *,
    id: list[str] | None = None,
    login: list[str] | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get(
    self,
    *,
    id: list[str] | None = None,
    login: list[str] | None = None,
    validate: bool | None = None,
  ) -> UsersFrame: ...
  async def get(
    self,
    *,
    id: list[str] | None = None,
    login: list[str] | None = None,
    validate: bool | None = None,
  ) -> UsersFrame:
    """Look up accounts by id, by login name, or by both. At most 100 across the two, and an id or login that does not exist is left out of the answer rather than erroring.

    Args:
      id: User ids to look up, such as `141981764`. Sent as repeated `id` query parameters. At most 100 ids and logins together.
      login: Login names to look up, such as `twitchdev`. Sent as repeated `login` query parameters. At most 100 ids and logins together.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-users)
    """
    request: Request = Request()
    if id is not None:
      request['id'] = id
    if login is not None:
      request['login'] = login
    return await self.request(
      request,
      method='GET',
      path='/helix/users',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=UsersFrame,
    )
