# Generated by truewire — do not edit by hand.
from .get import Get


class Videos(Get):
  """Published videos: a broadcaster's past broadcasts, highlights and uploads, paged by cursor.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-videos)
  """
