# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import Pagination


class MutedSegment(TypedDict):
  """One stretch of the video Twitch Audio Recognition muted."""

  duration: int
  """How long the muted stretch lasts, in seconds."""
  offset: int
  """How far into the video the muted stretch begins, in seconds."""


class Request(TypedDict):
  """Which videos, and which page of them."""

  id: NotRequired[list[str]]
  """Video ids to get, such as `335921245`. Sent as repeated `id` query parameters; at most 100. Mutually exclusive with `user_id` and `game_id`."""
  user_id: NotRequired[str]
  """The broadcaster whose videos to get. Mutually exclusive with `id` and `game_id`."""
  game_id: NotRequired[str]
  """The category whose videos to get, at most 500 of them. Mutually exclusive with `id` and `user_id`."""
  language: NotRequired[str]
  """Only videos broadcast in this language, as an ISO 639-1 two-letter code, or `other`. Only alongside `game_id`."""
  period: NotRequired[Literal['all', 'day', 'week', 'month']]
  """Only videos published within this period. Defaults to `all`. Only alongside `game_id` or `user_id`."""
  sort: NotRequired[Literal['time', 'trending', 'views']]
  """The order to return videos in: newest first, biggest gains in viewership first, or most viewed first. Defaults to `time`. Only alongside `game_id` or `user_id`."""
  type: NotRequired[Literal['all', 'archive', 'highlight', 'upload']]
  """Only videos of this type. Defaults to `all`. Only alongside `game_id` or `user_id`."""
  first: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 20."""
  after: NotRequired[str]
  """Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page."""
  before: NotRequired[str]
  """Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`."""


class Video(TypedDict):
  """One published video."""

  id: str
  """An ID that identifies the video."""
  stream_id: NotRequired[str | None]
  """The broadcast this video was recorded from; null unless the video is an `archive`."""
  user_id: str
  """The ID of the broadcaster that owns the video."""
  user_login: str
  """The broadcaster's login name."""
  user_name: str
  """The broadcaster's display name."""
  title: str
  """The video's title."""
  description: str
  """The video's description."""
  created_at: TimestampIso
  """When the video was created."""
  published_at: TimestampIso
  """When the video was published."""
  url: str
  """The video's URL on twitch.tv."""
  thumbnail_url: str
  """A URL to a thumbnail, with `%{width}` and `%{height}` placeholders to replace with the size you want. Twitch currently serves only 320 by 180."""
  viewable: Literal['public']
  """The video's viewable state; always `public`."""
  view_count: int
  """How many times the video has been watched."""
  language: str
  """The language the video was broadcast in, as an ISO 639-1 two-letter code, or `other`."""
  type: Literal['archive', 'highlight', 'upload']
  """The video's type: a past broadcast, a highlight cut from one, or a video the broadcaster uploaded."""
  duration: str
  """The video's length, written the way Twitch writes durations: `3m21s` is three minutes and twenty-one seconds."""
  muted_segments: NotRequired[list[MutedSegment] | None]
  """The stretches Twitch Audio Recognition muted; null where none were."""


class VideosFrame(TypedDict):
  """The wire frame: one page of videos, and the cursor for the next."""

  data: list[Video]
  """The videos on this page."""
  pagination: NotRequired[Pagination]


class Get(Endpoint):
  """Published videos, by video id, by broadcaster or by category. Exactly one of `id`, `user_id` and `game_id` is given; the remaining filters apply only alongside `user_id` or `game_id`."""

  @overload
  def get_paged(
    self,
    id: list[str] | None = None,
    *,
    user_id: str | None = None,
    game_id: str | None = None,
    language: str | None = None,
    period: Literal['all', 'day', 'week', 'month'] | None = None,
    sort: Literal['time', 'trending', 'views'] | None = None,
    type: Literal['all', 'archive', 'highlight', 'upload'] | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def get_paged(
    self,
    id: list[str] | None = None,
    *,
    user_id: str | None = None,
    game_id: str | None = None,
    language: str | None = None,
    period: Literal['all', 'day', 'week', 'month'] | None = None,
    sort: Literal['time', 'trending', 'views'] | None = None,
    type: Literal['all', 'archive', 'highlight', 'upload'] | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Video, str]: ...
  def get_paged(
    self,
    id: list[str] | None = None,
    *,
    user_id: str | None = None,
    game_id: str | None = None,
    language: str | None = None,
    period: Literal['all', 'day', 'week', 'month'] | None = None,
    sort: Literal['time', 'trending', 'views'] | None = None,
    type: Literal['all', 'archive', 'highlight', 'upload'] | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Video, str]:
    """Published videos, by video id, by broadcaster or by category. Exactly one of `id`, `user_id` and `game_id` is given; the remaining filters apply only alongside `user_id` or `game_id`.

    Paged variant of `get`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      id: Video ids to get, such as `335921245`. Sent as repeated `id` query parameters; at most 100. Mutually exclusive with `user_id` and `game_id`.
      user_id: The broadcaster whose videos to get. Mutually exclusive with `id` and `game_id`.
      game_id: The category whose videos to get, at most 500 of them. Mutually exclusive with `id` and `user_id`.
      language: Only videos broadcast in this language, as an ISO 639-1 two-letter code, or `other`. Only alongside `game_id`.
      period: Only videos published within this period. Defaults to `all`. Only alongside `game_id` or `user_id`.
      sort: The order to return videos in: newest first, biggest gains in viewership first, or most viewed first. Defaults to `time`. Only alongside `game_id` or `user_id`.
      type: Only videos of this type. Defaults to `all`. Only alongside `game_id` or `user_id`.
      first: Rows per page. Range [1, 100]; defaults to 20.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-videos)
    """

    async def next(after: str) -> tuple[list[Video], str | None]:
      response = await self.get(
        id,
        user_id=user_id,
        game_id=game_id,
        language=language,
        period=period,
        sort=sort,
        type=type,
        first=first,
        before=before,
        after=(after or None),
        validate=validate,
      )
      rows = response.get('data')
      state_0 = response.get('pagination')
      state = state_0.get('cursor') if state_0 is not None else None
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def get(
    self,
    id: list[str] | None = None,
    *,
    user_id: str | None = None,
    game_id: str | None = None,
    language: str | None = None,
    period: Literal['all', 'day', 'week', 'month'] | None = None,
    sort: Literal['time', 'trending', 'views'] | None = None,
    type: Literal['all', 'archive', 'highlight', 'upload'] | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get(
    self,
    id: list[str] | None = None,
    *,
    user_id: str | None = None,
    game_id: str | None = None,
    language: str | None = None,
    period: Literal['all', 'day', 'week', 'month'] | None = None,
    sort: Literal['time', 'trending', 'views'] | None = None,
    type: Literal['all', 'archive', 'highlight', 'upload'] | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> VideosFrame: ...
  async def get(
    self,
    id: list[str] | None = None,
    *,
    user_id: str | None = None,
    game_id: str | None = None,
    language: str | None = None,
    period: Literal['all', 'day', 'week', 'month'] | None = None,
    sort: Literal['time', 'trending', 'views'] | None = None,
    type: Literal['all', 'archive', 'highlight', 'upload'] | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> VideosFrame:
    """Published videos, by video id, by broadcaster or by category. Exactly one of `id`, `user_id` and `game_id` is given; the remaining filters apply only alongside `user_id` or `game_id`.

    Args:
      id: Video ids to get, such as `335921245`. Sent as repeated `id` query parameters; at most 100. Mutually exclusive with `user_id` and `game_id`.
      user_id: The broadcaster whose videos to get. Mutually exclusive with `id` and `game_id`.
      game_id: The category whose videos to get, at most 500 of them. Mutually exclusive with `id` and `user_id`.
      language: Only videos broadcast in this language, as an ISO 639-1 two-letter code, or `other`. Only alongside `game_id`.
      period: Only videos published within this period. Defaults to `all`. Only alongside `game_id` or `user_id`.
      sort: The order to return videos in: newest first, biggest gains in viewership first, or most viewed first. Defaults to `time`. Only alongside `game_id` or `user_id`.
      type: Only videos of this type. Defaults to `all`. Only alongside `game_id` or `user_id`.
      first: Rows per page. Range [1, 100]; defaults to 20.
      after: Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-videos)
    """
    request: Request = Request()
    if id is not None:
      request['id'] = id
    if user_id is not None:
      request['user_id'] = user_id
    if game_id is not None:
      request['game_id'] = game_id
    if language is not None:
      request['language'] = language
    if period is not None:
      request['period'] = period
    if sort is not None:
      request['sort'] = sort
    if type is not None:
      request['type'] = type
    if first is not None:
      request['first'] = first
    if after is not None:
      request['after'] = after
    if before is not None:
      request['before'] = before
    return await self.request(
      request,
      method='GET',
      path='/helix/videos',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=VideosFrame,
    )
