# Generated by truewire — do not edit by hand.
from .get import Get
from .top import Top


class Games(Get, Top):
  """Categories and games: looked up by id, name or IGDB id, or ranked by how many people are watching them right now.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-games)
  """
