# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import Game


class Request(TypedDict):
  """Which categories to look up."""

  id: NotRequired[list[str]]
  """Category ids to look up, such as `509670`. Sent as repeated `id` query parameters."""
  name: NotRequired[list[str]]
  """Category names to look up, matched exactly, such as `Science & Technology`. Sent as repeated `name` query parameters."""
  igdb_id: NotRequired[list[str]]
  """IGDB ids to look up. Sent as repeated `igdb_id` query parameters."""


class GamesFrame(TypedDict):
  """The wire frame. `/helix/games` does not page, so it carries `data` alone."""

  data: list[Game]
  """The categories found; empty when none of the ids or names matched."""


class Get(Endpoint):
  """Look up categories and games by id, by exact name, or by IGDB id. At most 100 across the three; a name that does not match exactly is left out of the answer."""

  @overload
  async def get(
    self,
    *,
    id: list[str] | None = None,
    name: list[str] | None = None,
    igdb_id: list[str] | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get(
    self,
    *,
    id: list[str] | None = None,
    name: list[str] | None = None,
    igdb_id: list[str] | None = None,
    validate: bool | None = None,
  ) -> GamesFrame: ...
  async def get(
    self,
    *,
    id: list[str] | None = None,
    name: list[str] | None = None,
    igdb_id: list[str] | None = None,
    validate: bool | None = None,
  ) -> GamesFrame:
    """Look up categories and games by id, by exact name, or by IGDB id. At most 100 across the three; a name that does not match exactly is left out of the answer.

    Args:
      id: Category ids to look up, such as `509670`. Sent as repeated `id` query parameters.
      name: Category names to look up, matched exactly, such as `Science & Technology`. Sent as repeated `name` query parameters.
      igdb_id: IGDB ids to look up. Sent as repeated `igdb_id` query parameters.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-games)
    """
    request: Request = Request()
    if id is not None:
      request['id'] = id
    if name is not None:
      request['name'] = name
    if igdb_id is not None:
      request['igdb_id'] = igdb_id
    return await self.request(
      request,
      method='GET',
      path='/helix/games',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=GamesFrame,
    )
