# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import Game, Pagination


class Request(TypedDict):
  """Which page of the ranking."""

  first: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 20."""
  after: NotRequired[str]
  """Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page."""
  before: NotRequired[str]
  """Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`."""


class TopGamesFrame(TypedDict):
  """The wire frame: one page of the ranking, and the cursor for the next."""

  data: list[Game]
  """The categories on this page, most watched first."""
  pagination: NotRequired[Pagination]


class Top(Endpoint):
  """The categories being watched most right now, most watched first, paged by cursor."""

  @overload
  def top_paged(
    self,
    first: int | None = None,
    *,
    before: str | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def top_paged(
    self,
    first: int | None = None,
    *,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Game, str]: ...
  def top_paged(
    self,
    first: int | None = None,
    *,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Game, str]:
    """The categories being watched most right now, most watched first, paged by cursor.

    Paged variant of `top`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      first: Rows per page. Range [1, 100]; defaults to 20.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-top-games)
    """

    async def next(after: str) -> tuple[list[Game], str | None]:
      response = await self.top(first, before=before, after=(after or None), validate=validate)
      rows = response.get('data')
      state_0 = response.get('pagination')
      state = state_0.get('cursor') if state_0 is not None else None
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def top(
    self,
    first: int | None = None,
    *,
    after: str | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def top(
    self,
    first: int | None = None,
    *,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> TopGamesFrame: ...
  async def top(
    self,
    first: int | None = None,
    *,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> TopGamesFrame:
    """The categories being watched most right now, most watched first, paged by cursor.

    Args:
      first: Rows per page. Range [1, 100]; defaults to 20.
      after: Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-top-games)
    """
    request: Request = Request()
    if first is not None:
      request['first'] = first
    if after is not None:
      request['after'] = after
    if before is not None:
      request['before'] = before
    return await self.request(
      request,
      method='GET',
      path='/helix/games/top',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=TopGamesFrame,
    )
