# Generated by truewire — do not edit by hand.
from functools import cached_property
from .channels import Channels
from .clips import Clips
from .eventsub import Eventsub
from .games import Games
from .streams import Streams
from .users import Users
from .videos import Videos
from .websocket import Websocket
from twitch_helix.core import ClientBase


class Twitch(ClientBase):
  """The Twitch Helix API: users, live streams, videos, clips, categories and channels, plus EventSub — the subscriptions over HTTP and the events they deliver over one WebSocket. Every call authenticates with an application client id and an app access token minted from the client credentials flow.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/)
  """

  @cached_property
  def channels(self) -> Channels:
    """Channel settings: the title, category, language, tags and content labels a broadcaster is streaming or last streamed under.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-channel-information)
    """
    return Channels(client=self.client)

  @cached_property
  def clips(self) -> Clips:
    """Clips captured from a broadcast, by clip id, by broadcaster or by category, paged by cursor.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-clips)
    """
    return Clips(client=self.client)

  @cached_property
  def eventsub(self) -> Eventsub:
    """EventSub subscriptions over HTTP: what the application listens for, and on whose channel. A subscription created here is what makes events arrive on the socket that `websocket.events()` opens.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/eventsub/manage-subscriptions/)
    """
    return Eventsub(client=self.client)

  @cached_property
  def games(self) -> Games:
    """Categories and games: looked up by id, name or IGDB id, or ranked by how many people are watching them right now.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-games)
    """
    return Games(client=self.client)

  @cached_property
  def streams(self) -> Streams:
    """Live broadcasts happening right now, filtered by broadcaster, category or language, ordered by viewer count and paged by cursor.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-streams)
    """
    return Streams(client=self.client)

  @cached_property
  def users(self) -> Users:
    """Accounts, by id or by login name (`GET /helix/users`).

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-users)
    """
    return Users(client=self.client)

  @cached_property
  def videos(self) -> Videos:
    """Published videos: a broadcaster's past broadcasts, highlights and uploads, paged by cursor.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-videos)
    """
    return Videos(client=self.client)

  @cached_property
  def websocket(self) -> Websocket:
    """EventSub's WebSocket transport: one socket that opens with a session id and then carries every event the application has subscribed that session to.

    References:
      - [Upstream docs](https://dev.twitch.tv/docs/eventsub/handling-websocket-events/)
    """
    return Websocket(client=self.socket)
