# Generated by truewire — do not edit by hand.
"""Shapes shared by two or more endpoints under the client root, generated from `spec/schemas.json`."""

from typing_extensions import Literal, NotRequired, TypedDict
from truewire_core.types import TimestampIso


class EventSubTransport(TypedDict):
  """How Twitch delivers a subscription's notifications, as it reports them back. The fields beyond `method` are the ones that method uses."""

  method: Literal['webhook', 'websocket', 'conduit']
  """The transport method."""
  callback: NotRequired[str]
  """The HTTPS callback URL notifications are sent to, for `webhook`."""
  session_id: NotRequired[str]
  """The WebSocket session the notifications are sent to, for `websocket`: the `id` of the `session_welcome` message that opened it."""
  connected_at: NotRequired[TimestampIso]
  """When the WebSocket connection was established, for `websocket`."""
  disconnected_at: NotRequired[TimestampIso]
  """When the WebSocket connection was lost, for `websocket`."""
  conduit_id: NotRequired[str]
  """The conduit the notifications are sent to, for `conduit`."""


class Game(TypedDict):
  """One category or game, as `/helix/games` and `/helix/games/top` list it."""

  id: str
  """An ID that identifies the category or game."""
  name: str
  """The category's or game's name."""
  box_art_url: str
  """A URL to the category's or game's box art, with a `{width}x{height}` placeholder to replace with the size you want, in pixels."""
  igdb_id: NotRequired[str]
  """The ID that IGDB uses to identify this game. An empty string where Twitch has no IGDB ID for it."""


class Pagination(TypedDict):
  """The cursor Helix pages every list with. Twitch sends this object *empty* on the last page rather than omitting it or nulling the cursor, so an absent `cursor` is how a walk ends."""

  cursor: NotRequired[str]
  """Opaque cursor. Pass it as the next request's `after` (or `before`, paging backwards); absent once there are no more pages."""


class EventSubSubscription(TypedDict):
  """One EventSub subscription: what it listens for, on whose channel, and where the events go. The same shape comes back from creating one, from listing them, and inside a `notification` or `revocation` message on the socket."""

  id: str
  """An ID that identifies the subscription."""
  status: str
  """The subscription's status. Events arrive only for `enabled`. The other values say why they stopped: `webhook_callback_verification_pending`, `webhook_callback_verification_failed`, `notification_failures_exceeded`, `authorization_revoked`, `moderator_removed`, `user_removed`, `chat_user_banned`, `version_removed`, `beta_maintenance`, and the `websocket_*` and `conduit_*` reasons. Left a bare string on purpose; see the endpoint's notes."""
  type: str
  """The subscription type, such as `stream.online`, `channel.follow` or `channel.chat.message`."""
  version: str
  """The version of that subscription type, such as `1` or `2`."""
  condition: dict[str, str]
  """The parameter values for this subscription type: `broadcaster_user_id`, `user_id`, `moderator_user_id` and so on. Which keys are required is a fact about the subscription type, so the shape is a map of strings."""
  created_at: TimestampIso
  """When the subscription was created."""
  transport: EventSubTransport
  cost: int
  """What this subscription counts against the application's total cost limit. A subscription the user authorized usually costs 0."""
