# Generated by truewire — do not edit by hand.
from .get import Get


class Channels(Get):
  """Channel settings: the title, category, language, tags and content labels a broadcaster is streaming or last streamed under.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-channel-information)
  """
