# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint


class Channel(TypedDict):
  """One channel's settings."""

  broadcaster_id: str
  """An ID that identifies the broadcaster."""
  broadcaster_login: str
  """The broadcaster's login name."""
  broadcaster_name: str
  """The broadcaster's display name."""
  broadcaster_language: str
  """The broadcaster's preferred language, as an ISO 639-1 two-letter code, or `other`."""
  game_id: str
  """The category being played or last played; an empty string for a broadcaster that never has."""
  game_name: str
  """The name of that category; an empty string for a broadcaster that never played one."""
  title: str
  """The title of the current or last broadcast; an empty string for a broadcaster that never streamed."""
  delay: int
  """The broadcaster's stream delay setting, in seconds. Zero unless the call used that broadcaster's own user access token and they are a partner who set one."""
  tags: NotRequired[list[str]]
  """The tags applied to the channel."""
  content_classification_labels: NotRequired[list[str]]
  """The content classification labels applied to the channel."""
  is_branded_content: NotRequired[bool]
  """Whether the channel is flagged as branded content."""


class Request(TypedDict):
  """Whose channels to read."""

  broadcaster_id: list[str]
  """Broadcaster ids whose channels to read, such as `141981764`. Sent as repeated `broadcaster_id` query parameters; at most 100."""


class ChannelsFrame(TypedDict):
  """The wire frame. `/helix/channels` does not page, so it carries `data` alone."""

  data: list[Channel]
  """The channels found; empty when none of the ids matched."""


class Get(Endpoint):
  """Channel settings for one or more broadcasters: what they are streaming or last streamed, under which title, category, language, tags and content labels."""

  @overload
  async def get(
    self,
    broadcaster_id: list[str],
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get(
    self,
    broadcaster_id: list[str],
    *,
    validate: bool | None = None,
  ) -> ChannelsFrame: ...
  async def get(
    self,
    broadcaster_id: list[str],
    *,
    validate: bool | None = None,
  ) -> ChannelsFrame:
    """Channel settings for one or more broadcasters: what they are streaming or last streamed, under which title, category, language, tags and content labels.

    Args:
      broadcaster_id: Broadcaster ids whose channels to read, such as `141981764`. Sent as repeated `broadcaster_id` query parameters; at most 100.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-channel-information)
    """
    return await self.request(
      Request(broadcaster_id=broadcaster_id),
      method='GET',
      path='/helix/channels',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=ChannelsFrame,
    )
