# Generated by truewire — do not edit by hand.
from .events import Events


class Websocket(Events):
  """EventSub's WebSocket transport: one socket that opens with a session id and then carries every event the application has subscribed that session to.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/eventsub/handling-websocket-events/)
  """
