# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from truewire_core.util import StreamManager
from typing_extensions import Any, Literal, NotRequired, TypedDict
from twitch_helix.core import StreamEndpoint
from twitch_helix.schemas import EventSubSubscription


class MessageMetadata(TypedDict):
  """Which message this is, and when Twitch sent it."""

  message_id: str
  """An ID that identifies this message, unique per session."""
  message_type: Literal[
    'session_welcome', 'session_keepalive', 'notification', 'session_reconnect', 'revocation'
  ]
  """Which kind of message this is."""
  message_timestamp: TimestampIso
  """When Twitch sent the message, to the nanosecond."""
  subscription_type: NotRequired[str]
  """The subscription type this message is about, on a `notification` or a `revocation`."""
  subscription_version: NotRequired[str]
  """The version of that subscription type, on a `notification` or a `revocation`."""


class Parameters(TypedDict):
  """The socket's own settings, sent as the connection URL's query string. The subscriptions are not here; they are created over HTTP against the session id the welcome message carries."""

  keepalive_timeout_seconds: NotRequired[int]
  """How long Twitch may go without sending anything before it sends a `session_keepalive`, and how long the client should wait before treating the connection as lost. A whole number of seconds between 10 and 600; Twitch moves a numeric value outside that range to the nearest allowed one. Defaults to 10."""


class Session(TypedDict):
  """The WebSocket session this connection carries."""

  id: str
  """The session id. This is the value an EventSub subscription names as its `transport.session_id` to deliver here."""
  status: str
  """The session's state: `connected` on a welcome, `reconnecting` on a reconnect. Left a bare string on purpose; see the notes."""
  connected_at: NotRequired[TimestampIso]
  """When the connection was established."""
  keepalive_timeout_seconds: NotRequired[int | None]
  """How long Twitch will go without sending anything before sending a keepalive. Null on a `session_reconnect`, where the setting belongs to the new connection."""
  reconnect_url: NotRequired[str | None]
  """The URL to reconnect to, on a `session_reconnect`; null otherwise. Use it exactly as given: it carries its own query string. The old connection keeps delivering until the new one has been welcomed."""


class MessagePayload(TypedDict):
  """What the message carries. Empty on a `session_keepalive`, a `session` on a `session_welcome` or `session_reconnect`, a `subscription` on a `revocation`, and both a `subscription` and an `event` on a `notification`."""

  session: NotRequired[Session]
  subscription: NotRequired[EventSubSubscription]
  event: NotRequired[dict[str, Any]]
  """The event itself, on a `notification`. Its fields are a fact about `metadata.subscription_type` — a `channel.follow` event carries `user_id` and `followed_at`, a `stream.online` event carries `type` and `started_at` — so it is kept as a map. See the notes."""


class EventSubMessage(TypedDict):
  """One message. `metadata.message_type` says which of the five kinds it is and which parts of `payload` are filled in."""

  metadata: MessageMetadata
  payload: NotRequired[MessagePayload]


class Events(StreamEndpoint):
  """Open an EventSub WebSocket and read every message it pushes. The first message is always `session_welcome`, carrying the session id; subscriptions created against that id with `eventsub.subscribe(...)` then deliver their events here as `notification` messages. `session_keepalive` says the connection is healthy, `session_reconnect` hands over a URL to move to, and `revocation` says a subscription has stopped and why. Nothing is ever sent to the socket: Twitch closes a connection that receives anything but a pong."""

  def events(
    self,
    keepalive_timeout_seconds: int | None = None,
    *,
    validate: bool | None = None,
  ) -> StreamManager[EventSubMessage, Any, Any]:
    """Open an EventSub WebSocket and read every message it pushes. The first message is always `session_welcome`, carrying the session id; subscriptions created against that id with `eventsub.subscribe(...)` then deliver their events here as `notification` messages. `session_keepalive` says the connection is healthy, `session_reconnect` hands over a URL to move to, and `revocation` says a subscription has stopped and why. Nothing is ever sent to the socket: Twitch closes a connection that receives anything but a pong.

    Args:
      keepalive_timeout_seconds: How long Twitch may go without sending anything before it sends a `session_keepalive`, and how long the client should wait before treating the connection as lost. A whole number of seconds between 10 and 600; Twitch moves a numeric value outside that range to the nearest allowed one. Defaults to 10.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://dev.twitch.tv/docs/eventsub/handling-websocket-events/)
    """
    parameters: Parameters = Parameters()
    if keepalive_timeout_seconds is not None:
      parameters['keepalive_timeout_seconds'] = keepalive_timeout_seconds
    return self.subscribe(
      'ws',
      parameters,
      validate=validate,
      request_type=Parameters,
      response_type=EventSubMessage,
    )
