# Generated by truewire — do not edit by hand.
from .subscribe import Subscribe
from .subscriptions import Subscriptions


class Eventsub(Subscribe, Subscriptions):
  """EventSub subscriptions over HTTP: what the application listens for, and on whose channel. A subscription created here is what makes events arrive on the socket that `websocket.events()` opens.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/eventsub/manage-subscriptions/)
  """
