# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import EventSubSubscription, Pagination


class Request(TypedDict):
  """Which subscriptions, and which page of them."""

  status: NotRequired[
    Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
  ]
  """Only subscriptions in this state."""
  type: NotRequired[str]
  """Only subscriptions of this type, such as `stream.online`."""
  user_id: NotRequired[str]
  """Only subscriptions whose condition names this user id."""
  subscription_id: NotRequired[str]
  """Only the subscription with this id, if the application owns it."""
  conduit_id: NotRequired[str]
  """Only subscriptions delivered to this conduit."""
  after: NotRequired[str]
  """Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page."""


class SubscriptionsFrame(TypedDict):
  """The wire frame: one page of subscriptions, what they cost in total, and the cursor for the next page."""

  data: list[EventSubSubscription]
  """The subscriptions on this page, oldest first."""
  total: NotRequired[int]
  """How many subscriptions the application currently has."""
  total_cost: NotRequired[int]
  """The sum of every subscription's cost."""
  max_total_cost: NotRequired[int]
  """The most the application is allowed to spend on subscriptions."""
  pagination: NotRequired[Pagination]


class Subscriptions(Endpoint):
  """The EventSub subscriptions this application has created, oldest first, paged by cursor. The filters are mutually exclusive: give at most one. An app access token lists the webhook and conduit subscriptions; the WebSocket ones belong to the user token that created them."""

  @overload
  def subscriptions_paged(
    self,
    status: Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
    | None = None,
    *,
    type: str | None = None,
    user_id: str | None = None,
    subscription_id: str | None = None,
    conduit_id: str | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def subscriptions_paged(
    self,
    status: Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
    | None = None,
    *,
    type: str | None = None,
    user_id: str | None = None,
    subscription_id: str | None = None,
    conduit_id: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[EventSubSubscription, str]: ...
  def subscriptions_paged(
    self,
    status: Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
    | None = None,
    *,
    type: str | None = None,
    user_id: str | None = None,
    subscription_id: str | None = None,
    conduit_id: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[EventSubSubscription, str]:
    """The EventSub subscriptions this application has created, oldest first, paged by cursor. The filters are mutually exclusive: give at most one. An app access token lists the webhook and conduit subscriptions; the WebSocket ones belong to the user token that created them.

    Paged variant of `subscriptions`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      status: Only subscriptions in this state.
      type: Only subscriptions of this type, such as `stream.online`.
      user_id: Only subscriptions whose condition names this user id.
      subscription_id: Only the subscription with this id, if the application owns it.
      conduit_id: Only subscriptions delivered to this conduit.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions)
    """

    async def next(after: str) -> tuple[list[EventSubSubscription], str | None]:
      response = await self.subscriptions(
        status,
        type=type,
        user_id=user_id,
        subscription_id=subscription_id,
        conduit_id=conduit_id,
        after=(after or None),
        validate=validate,
      )
      rows = response.get('data')
      state_0 = response.get('pagination')
      state = state_0.get('cursor') if state_0 is not None else None
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def subscriptions(
    self,
    status: Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
    | None = None,
    *,
    type: str | None = None,
    user_id: str | None = None,
    subscription_id: str | None = None,
    conduit_id: str | None = None,
    after: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def subscriptions(
    self,
    status: Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
    | None = None,
    *,
    type: str | None = None,
    user_id: str | None = None,
    subscription_id: str | None = None,
    conduit_id: str | None = None,
    after: str | None = None,
    validate: bool | None = None,
  ) -> SubscriptionsFrame: ...
  async def subscriptions(
    self,
    status: Literal[
      'enabled',
      'webhook_callback_verification_pending',
      'webhook_callback_verification_failed',
      'notification_failures_exceeded',
      'authorization_revoked',
      'moderator_removed',
      'user_removed',
      'chat_user_banned',
      'version_removed',
      'beta_maintenance',
      'websocket_disconnected',
      'websocket_failed_ping_pong',
      'websocket_received_inbound_traffic',
      'websocket_connection_unused',
      'websocket_internal_error',
      'websocket_network_timeout',
      'websocket_network_error',
      'websocket_failed_to_reconnect',
      'conduit_deleted',
    ]
    | None = None,
    *,
    type: str | None = None,
    user_id: str | None = None,
    subscription_id: str | None = None,
    conduit_id: str | None = None,
    after: str | None = None,
    validate: bool | None = None,
  ) -> SubscriptionsFrame:
    """The EventSub subscriptions this application has created, oldest first, paged by cursor. The filters are mutually exclusive: give at most one. An app access token lists the webhook and conduit subscriptions; the WebSocket ones belong to the user token that created them.

    Args:
      status: Only subscriptions in this state.
      type: Only subscriptions of this type, such as `stream.online`.
      user_id: Only subscriptions whose condition names this user id.
      subscription_id: Only the subscription with this id, if the application owns it.
      conduit_id: Only subscriptions delivered to this conduit.
      after: Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions)
    """
    request: Request = Request()
    if status is not None:
      request['status'] = status
    if type is not None:
      request['type'] = type
    if user_id is not None:
      request['user_id'] = user_id
    if subscription_id is not None:
      request['subscription_id'] = subscription_id
    if conduit_id is not None:
      request['conduit_id'] = conduit_id
    if after is not None:
      request['after'] = after
    return await self.request(
      request,
      method='GET',
      path='/helix/eventsub/subscriptions',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=SubscriptionsFrame,
    )
