# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import EventSubSubscription


class CreateSubscriptionTransport(TypedDict):
  """Where Twitch should deliver this subscription's notifications."""

  method: Literal['webhook', 'websocket', 'conduit']
  """The transport method. `websocket` is the one this client opens a socket for."""
  session_id: NotRequired[str]
  """The WebSocket session to deliver to, for `websocket`: the `id` of the `session_welcome` message that opened the socket."""
  callback: NotRequired[str]
  """The HTTPS callback URL to deliver to, for `webhook`. Port 443, no redirects."""
  secret: NotRequired[str]
  """The secret Twitch signs webhook deliveries with, for `webhook`: 10 to 100 ASCII characters. Never recorded; see the notes."""
  conduit_id: NotRequired[str]
  """The conduit to deliver to, for `conduit`."""


class CreateSubscriptionFrame(TypedDict):
  """The wire frame: the one subscription just created, and what the application has spent on subscriptions in total."""

  data: list[EventSubSubscription]
  """A list holding the one subscription created."""
  total: NotRequired[int]
  """How many subscriptions the application currently has."""
  total_cost: NotRequired[int]
  """The sum of every subscription's cost."""
  max_total_cost: NotRequired[int]
  """The most the application is allowed to spend on subscriptions."""


class Request(TypedDict):
  """The subscription to create. Sent as a JSON body."""

  type: str
  """The subscription type to create, such as `stream.online`, `channel.follow` or `channel.chat.message`."""
  version: str
  """The version of that subscription type, such as `1` or `2`. Which versions exist is a fact about the type."""
  condition: dict[str, str]
  """The parameter values for this subscription type: `broadcaster_user_id`, `user_id`, `moderator_user_id` and so on. Which keys are required, and which scopes they need, is a fact about the subscription type."""
  transport: CreateSubscriptionTransport


class Subscribe(Endpoint):
  """Create an EventSub subscription: the event type to listen for, the condition saying whose events those are, and the transport to deliver them over. For the WebSocket transport that transport names the `session_id` from the `session_welcome` message of an open socket, and the events then arrive on that socket. Answered `202 Accepted` with the subscription as created."""

  @overload
  async def subscribe(
    self,
    *,
    type: str,
    version: str,
    condition: dict[str, str],
    transport: CreateSubscriptionTransport,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def subscribe(
    self,
    *,
    type: str,
    version: str,
    condition: dict[str, str],
    transport: CreateSubscriptionTransport,
    validate: bool | None = None,
  ) -> CreateSubscriptionFrame: ...
  async def subscribe(
    self,
    *,
    type: str,
    version: str,
    condition: dict[str, str],
    transport: CreateSubscriptionTransport,
    validate: bool | None = None,
  ) -> CreateSubscriptionFrame:
    """Create an EventSub subscription: the event type to listen for, the condition saying whose events those are, and the transport to deliver them over. For the WebSocket transport that transport names the `session_id` from the `session_welcome` message of an open socket, and the events then arrive on that socket. Answered `202 Accepted` with the subscription as created.

    Args:
      type: The subscription type to create, such as `stream.online`, `channel.follow` or `channel.chat.message`.
      version: The version of that subscription type, such as `1` or `2`. Which versions exist is a fact about the type.
      condition: The parameter values for this subscription type: `broadcaster_user_id`, `user_id`, `moderator_user_id` and so on. Which keys are required, and which scopes they need, is a fact about the subscription type.
      transport: Where Twitch should deliver this subscription's notifications.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#create-eventsub-subscription)
    """
    return await self.request(
      Request(type=type, version=version, condition=condition, transport=transport),
      method='POST',
      path='/helix/eventsub/subscriptions',
      meta={'token': 'user'},
      validate=validate,
      request_type=Request,
      response_type=CreateSubscriptionFrame,
    )
