# Generated by truewire — do not edit by hand.
from .get import Get


class Streams(Get):
  """Live broadcasts happening right now, filtered by broadcaster, category or language, ordered by viewer count and paged by cursor.

  References:
    - [Upstream docs](https://dev.twitch.tv/docs/api/reference/#get-streams)
  """
