# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from twitch_helix.core import Endpoint
from twitch_helix.schemas import Pagination


class Request(TypedDict):
  """Which live broadcasts, and which page of them."""

  user_id: NotRequired[list[str]]
  """Only these broadcasters, by user id. Sent as repeated `user_id` query parameters; at most 100."""
  user_login: NotRequired[list[str]]
  """Only these broadcasters, by login name, such as `twitchdev`. Sent as repeated `user_login` query parameters; at most 100."""
  game_id: NotRequired[list[str]]
  """Only broadcasts of these categories, by category id. Sent as repeated `game_id` query parameters; at most 100."""
  type: NotRequired[Literal['all', 'live']]
  """The type of broadcast to return. Defaults to `all`."""
  language: NotRequired[list[str]]
  """Only broadcasts in these languages, as ISO 639-1 two-letter codes, or `other` for a language Twitch does not list. Sent as repeated `language` query parameters; at most 100."""
  first: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 20."""
  after: NotRequired[str]
  """Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page."""
  before: NotRequired[str]
  """Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`."""


class Stream(TypedDict):
  """One live broadcast."""

  id: str
  """An ID that identifies this broadcast. The video on demand it becomes carries the same id as its `stream_id`."""
  user_id: str
  """The ID of the broadcaster."""
  user_login: str
  """The broadcaster's login name."""
  user_name: str
  """The broadcaster's display name."""
  game_id: str
  """The ID of the category being streamed; an empty string when the channel has no category set."""
  game_name: str
  """The name of the category being streamed; an empty string when the channel has no category set."""
  type: str
  """The type of broadcast, `live`. An empty string where Twitch hit an error computing it. Left a bare string on purpose; see the notes."""
  title: str
  """The broadcast's title; an empty string if unset."""
  tags: NotRequired[list[str]]
  """The tags applied to the broadcast."""
  viewer_count: int
  """How many people are watching right now."""
  started_at: TimestampIso
  """When the broadcast began."""
  language: str
  """The language of the broadcast, as an ISO 639-1 two-letter code, or `other`."""
  thumbnail_url: str
  """A URL to a frame from the last five minutes of the broadcast, with a `{width}x{height}` placeholder to replace with the size you want, in pixels."""


class StreamsFrame(TypedDict):
  """The wire frame: one page of live broadcasts, and the cursor for the next."""

  data: list[Stream]
  """The live broadcasts on this page, most watched first."""
  pagination: NotRequired[Pagination]


class Get(Endpoint):
  """Live broadcasts, most watched first, filtered by broadcaster, category or language. A broadcaster who is not live is simply absent from the answer. Viewers come and go while a walk is in flight, so a stream can be seen twice or missed across pages."""

  @overload
  def get_paged(
    self,
    *,
    user_id: list[str] | None = None,
    user_login: list[str] | None = None,
    game_id: list[str] | None = None,
    type: Literal['all', 'live'] | None = None,
    language: list[str] | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def get_paged(
    self,
    *,
    user_id: list[str] | None = None,
    user_login: list[str] | None = None,
    game_id: list[str] | None = None,
    type: Literal['all', 'live'] | None = None,
    language: list[str] | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Stream, str]: ...
  def get_paged(
    self,
    *,
    user_id: list[str] | None = None,
    user_login: list[str] | None = None,
    game_id: list[str] | None = None,
    type: Literal['all', 'live'] | None = None,
    language: list[str] | None = None,
    first: int | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Stream, str]:
    """Live broadcasts, most watched first, filtered by broadcaster, category or language. A broadcaster who is not live is simply absent from the answer. Viewers come and go while a walk is in flight, so a stream can be seen twice or missed across pages.

    Paged variant of `get`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      user_id: Only these broadcasters, by user id. Sent as repeated `user_id` query parameters; at most 100.
      user_login: Only these broadcasters, by login name, such as `twitchdev`. Sent as repeated `user_login` query parameters; at most 100.
      game_id: Only broadcasts of these categories, by category id. Sent as repeated `game_id` query parameters; at most 100.
      type: The type of broadcast to return. Defaults to `all`.
      language: Only broadcasts in these languages, as ISO 639-1 two-letter codes, or `other` for a language Twitch does not list. Sent as repeated `language` query parameters; at most 100.
      first: Rows per page. Range [1, 100]; defaults to 20.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-streams)
    """

    async def next(after: str) -> tuple[list[Stream], str | None]:
      response = await self.get(
        user_id=user_id,
        user_login=user_login,
        game_id=game_id,
        type=type,
        language=language,
        first=first,
        before=before,
        after=(after or None),
        validate=validate,
      )
      rows = response.get('data')
      state_0 = response.get('pagination')
      state = state_0.get('cursor') if state_0 is not None else None
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def get(
    self,
    *,
    user_id: list[str] | None = None,
    user_login: list[str] | None = None,
    game_id: list[str] | None = None,
    type: Literal['all', 'live'] | None = None,
    language: list[str] | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get(
    self,
    *,
    user_id: list[str] | None = None,
    user_login: list[str] | None = None,
    game_id: list[str] | None = None,
    type: Literal['all', 'live'] | None = None,
    language: list[str] | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> StreamsFrame: ...
  async def get(
    self,
    *,
    user_id: list[str] | None = None,
    user_login: list[str] | None = None,
    game_id: list[str] | None = None,
    type: Literal['all', 'live'] | None = None,
    language: list[str] | None = None,
    first: int | None = None,
    after: str | None = None,
    before: str | None = None,
    validate: bool | None = None,
  ) -> StreamsFrame:
    """Live broadcasts, most watched first, filtered by broadcaster, category or language. A broadcaster who is not live is simply absent from the answer. Viewers come and go while a walk is in flight, so a stream can be seen twice or missed across pages.

    Args:
      user_id: Only these broadcasters, by user id. Sent as repeated `user_id` query parameters; at most 100.
      user_login: Only these broadcasters, by login name, such as `twitchdev`. Sent as repeated `user_login` query parameters; at most 100.
      game_id: Only broadcasts of these categories, by category id. Sent as repeated `game_id` query parameters; at most 100.
      type: The type of broadcast to return. Defaults to `all`.
      language: Only broadcasts in these languages, as ISO 639-1 two-letter codes, or `other` for a language Twitch does not list. Sent as repeated `language` query parameters; at most 100.
      first: Rows per page. Range [1, 100]; defaults to 20.
      after: Cursor for the next page, taken from `pagination.cursor` of the previous response; omit for the first page.
      before: Cursor for the previous page, taken from `pagination.cursor` of the previous response. The generated walk only pages forward, with `after`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://dev.twitch.tv/docs/api/reference/#get-streams)
    """
    request: Request = Request()
    if user_id is not None:
      request['user_id'] = user_id
    if user_login is not None:
      request['user_login'] = user_login
    if game_id is not None:
      request['game_id'] = game_id
    if type is not None:
      request['type'] = type
    if language is not None:
      request['language'] = language
    if first is not None:
      request['first'] = first
    if after is not None:
      request['after'] = after
    if before is not None:
      request['before'] = before
    return await self.request(
      request,
      method='GET',
      path='/helix/streams',
      meta={'token': 'app'},
      validate=validate,
      request_type=Request,
      response_type=StreamsFrame,
    )
